backend:
  name: github
  repo: 90090/social-circle
  branch: main
  auth_scope: "repo"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/homepage.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
