backend:
  name: github
  repo: 90090/social-circle
  branch: main
  auth_scope: "repo"

site_url: https://social-circlellc.netlify.app
display_url: https://social-circlellc.netlify.app

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src"  # Adjust based on where you store content
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
